# This file contains values from Cookiecutter

default_context:
  project_name: "pyutils"
  project_description: "pyutils is wrapper python base class for usability."
  organization: "TakashiAihara"
  license: "MIT"
  minimal_python_version: 3.10
  github_name: "TakashiAihara"
  email: "takashi.aihara.0523@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
